### PR TITLE
chore [CAM2-915]: removed from the phrase the redundant quote symbol.

### PR DESCRIPTION
**Pull request by bahalula**
https://campusil.atlassian.net/browse/CAM2-915

### CODE REVIEW

**Review by vladimirCampusGovIl — APPROVED** [review]

**Review by GlugovGrGlib — APPROVED** [review]

**Comment by GlugovGrGlib** [comment]
@bahalula sorry your solution doesn't work, it's required to remove the  {quote} from the English phrase as well, and remove it from the text in the file openedx/core/djangoapps/user_authn/views/login.py
Please ask Vladimir to check if those changes helped to compile tranlations. Current error:
```
./manage.py lms compilemessages -l ar -l he

Execution of msgfmt failed: /edx/app/edxapp/venvs/edxapp/src/extended-translations/extended_translations/conf/locale/he/LC_MESSAGES/django.po:12188: a format specification for argument 'quote' doesn't exist in 'msgstr'
```

**Review by GlugovGrGlib — CHANGES_REQUESTED** [review]
Remove the quote from the English phrase as well

**Comment by vladimirCampusGovIl** [comment]
> Please ask Vladimir to check if those changes helped to compile translations.

It's correct, in case value does not exist in Value it also needs to be removed from the Key phrase.

First, the next phase needs to be updated. "If you{quote}ve forgotten your password, ..."
After it, need to check and update the phrase in py file as Glib wrote.

**Comment by vladimirCampusGovIl** [comment]
@GlugovGrGlib, This change was applied by Eden in different PR. This one can be closed.

**Pull request closed without merging**
